CREATE TABLE IF NOT EXISTS users_storage (
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email varchar(50) NOT NULL,
                       name varchar(50) NOT NULL,
                       login varchar(50) NOT NULL,
                       birthday DATE NOT NULL

);

CREATE TABLE IF NOT EXISTS friends (
                       first_user_id INTEGER NOT NULL REFERENCES users_storage (id),
                       second_user_id INTEGER NOT NULL REFERENCES users_storage (id)
);

CREATE TABLE IF NOT EXISTS genre (
                       genre_id INTEGER PRIMARY KEY,
                       name VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS rate (
                       rate_id INTEGER PRIMARY KEY ,
                       name VARCHAR(10) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar(50) NOT NULL,
                       description varchar(200) NOT NULL,
                       release_date DATE NOT NULL ,
                       duration INTEGER CHECK duration > 0,
                       rate_id INTEGER REFERENCES rate(rate_id)
);

CREATE TABLE IF NOT EXISTS film_genre (
                       film_id INTEGER REFERENCES films(id),
                       genre_id INTEGER REFERENCES genre(genre_id),
                       UNIQUE (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likes (
                       film_id INTEGER REFERENCES films(id),
                       user_id INTEGER REFERENCES users_storage(id)
);